Repository gardener/gardener-extension-shoot-lakom-service, pull requests merged in 2023-12, with the labels that each got.

#54 Fix mitigation for NoMatchingSignature error
  pkg/lakom/verifysignature/verifier.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#57 Update golang to 1.21.5
  .test-defs/lifecycle.yaml
  Dockerfile
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#58 [release-v0.11] Automated cherry pick of #54: Fix mitigation for NoMatchingSignature error
  pkg/lakom/verifysignature/verifier.go
Labels: area/security, kind/bug, reviewed/lgtm, needs/ok-to-test, size/xs

#56 Capitalize log.Info messages
  pkg/lakom/verifysignature/verifier.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#60 Link cherry-pick script
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
