Repository gardener/gardener-extension-shoot-lakom-service, pull requests merged in 2023-08, with the labels that each got.

#29 Improve error checks
  pkg/lakom/verifysignature/verifier.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#28 Mitigate wrongly returned NoMatchingSignature error when context is canceled
  pkg/lakom/verifysignature/verifier.go
  pkg/lakom/verifysignature/verifier_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#30 Remove temporary code cleaning secrets from the namespace of the extension
  pkg/controller/seed/reconciler.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#31 Remove temporary code cleaning health condition from Extension resource
  pkg/controller/healthcheck/add.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#32 Update golang to 1.21.0
  .test-defs/lifecycle.yaml
  Dockerfile
  go.mod
  go.sum
Labels: reviewed/lgtm, needs/ok-to-test, size/s
