Repository gardener/gardener-extension-shoot-lakom-service, pull requests merged in 2025-03, with the labels that each got.

#146 Fix lakom to consider algorithm when making trusted keys unique
  pkg/lakom/config/config.go
  pkg/lakom/config/config_test.go
  pkg/lakom/verifysignature/admission.go
Labels: kind/bug, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#147 Update golang.org/x/crypto to v0.36.0
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/s

#118 Drop support for Shoots with Kubernetes version <= 1.26
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/service.yaml
  charts/gardener-extension-shoot-lakom-service/templates/poddisruptionbudget.yaml
  charts/lakom/charts/runtime/templates/poddisruptionbudget.yaml
  example/30-cluster.yaml
  example/controller-registration.yaml
  go.mod
  pkg/controller/lifecycle/actuator.go
  pkg/controller/lifecycle/actuator_test.go
  pkg/controller/seed/add.go
  pkg/controller/seed/reconciler.go
  pkg/controller/seed/reconciler_test.go
Labels: kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#154 Split scaffold helm deployment for admission in two
  skaffold.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#152 Add support for image pull secrets used in ControllerDeployments, Extensions and Gardenlets
  .ci/hack/component_descriptor
  cmd/gardener-extension-shoot-lakom-service/app/app.go
  go.mod
  go.sum
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/cmd/options.go
  pkg/controller/healthcheck/add.go
  pkg/controller/lifecycle/add.go
  pkg/lakom/resolvetag/admission.go
  pkg/lakom/verifysignature/admission.go
Labels: kind/api-change, reviewed/lgtm, needs/ok-to-test, size/xl

#130 Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/service.yaml
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#155 Remove RBAC wildcard references
  charts/gardener-extension-shoot-lakom-service/templates/rbac.yaml
  example/25-rbac.yaml
  example/controller-registration.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s
