Repository gardener/gardener-extension-shoot-lakom-service, pull requests merged in 2025-02, with the labels that each got.

#134 Publish separate admission Helm charts
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs, ci/broken-pipeline-definition

#124 Update github.com/gardener/gardener to v1.110.1
  Makefile
  go.mod
  go.sum
  hack/sast.sh
  pkg/admission/validator/lakom/shoot.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#131 Fake registry for tests
  docs/oci_registries.md
  pkg/lakom/resolvetag/admission_test.go
  pkg/lakom/resolvetag/resolver_test.go
  pkg/lakom/resolvetag/resolvetag_suite_test.go
  pkg/lakom/verifysignature/admission_test.go
  pkg/lakom/verifysignature/verifier_test.go
  pkg/lakom/verifysignature/verifysignature_suite_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl

#133 Prepare for deployment of admission controller by gardener-operator
  .reuse/dep5
  charts/gardener-extension-shoot-lakom-admission/Chart.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/application/.helmignore
  charts/gardener-extension-shoot-lakom-admission/charts/application/templates/_helpers.tpl
  charts/gardener-extension-shoot-lakom-admission/charts/application/templates/rbac.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/application/values.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/.helmignore
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/_helpers.tpl
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/service.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/values.yaml
  charts/gardener-extension-shoot-lakom-admission/templates/_helpers.tpl
  charts/gardener-extension-shoot-lakom-admission/values.yaml
  cmd/gardener-extension-shoot-lakom-admission/app/app.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/changes, needs/second-opinion, size/l, ci/broken-pipeline-definition

#143 Add support for projected kubeconfig in lakom chart
  charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/deployment.yaml
  charts/lakom/templates/deployment.yaml
  charts/lakom/templates/validatingwebhookconfiguration.yaml
  charts/lakom/values.yaml
Labels: area/security, area/ipcei, kind/bug, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#144 Split lakom chart into application and runtime subcharts
  .reuse/dep5
  charts/lakom/Chart.yaml
  charts/lakom/charts/application/Chart.yaml
  charts/lakom/charts/application/templates/mutatingwebhookconfiguration.yaml
  charts/lakom/charts/application/templates/rbac.yaml
  charts/lakom/charts/application/templates/validatingwebhookconfiguration.yaml
  charts/lakom/charts/application/values.yaml
  charts/lakom/charts/runtime/Chart.yaml
  charts/lakom/charts/runtime/templates/_helpers.tpl
  charts/lakom/charts/runtime/templates/configmap-lakom-config.yaml
  charts/lakom/charts/runtime/templates/deployment.yaml
  charts/lakom/charts/runtime/templates/poddisruptionbudget.yaml
  charts/lakom/charts/runtime/templates/priorityclass.yaml
  charts/lakom/charts/runtime/templates/secret-lakom-server-tls.yaml
  charts/lakom/charts/runtime/templates/secret-lakom-target-kubeconfig.yaml
  charts/lakom/charts/runtime/templates/service.yaml
  charts/lakom/charts/runtime/templates/serviceaccount.yaml
  charts/lakom/charts/runtime/templates/vpa.yaml
  charts/lakom/charts/runtime/values.yaml
  charts/lakom/values.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l
